#!/bin/bash
set -e

function run_test {
    git cat-file blob :"${1}" | jshint --filename "${1}" -
}

case "${1}" in
    --about )
        echo "Introduction of this hook"
        ;;
    --install )
        echo "Installing jshint"
        npm install -g jshint
        ;;
    * )
        if git rev-parse --verify HEAD >/dev/null 2>&1 ; then
            head="HEAD"
        else
            # First commit, use an empty tree
            head="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
        fi
        for file in `git diff-index --diff-filter=ACM --cached --name-only "${head}"` ; do
            filename=$(basename "$file")
            extension="${filename##*.}"
            if [ "$extension" = "js" ] || [ "$extension" = "json" ] ; then
                run_test "${file}"
            fi
        done
        ;;
esac
