#!/bin/bash
set -e

function run_test {
    git cat-file blob :"${1}" | jshint --filename "${1}" -
}

case "${1}" in
    --about )
        echo "Introduction of this hook"
        ;;
    --install )
        echo "Installing jshint"
        npm install -g jshint
        ;;
    * )
        for file in `git diff-index --cached --name-only HEAD` ; do
            filename=$(basename "$file")
            extension="${filename##*.}"
            if [ "$extension" = "js" ] || [ "$extension" = "json" ] ; then
                run_test "${file}"
            fi
        done
        ;;
esac
